services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8122:8121"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_HTTP_PORT=8121
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_LOG_LEVEL=info
