PORT: 3000
CLICKHOUSE_HOST: localhost
CLICKHOUSE_TCP_PORT: 9000
CLICKHOUSE_USER: admin
CLICKHOUSE_PASSWORD: password
CLICKHOUSE_DATABASE: dimo
DEVICES_APIGRPC_ADDR: localhost:8086
TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
TOKEN_EXCHANGE_ISSUER_URL: http://127.0.0.1:5556/dex
VEHICLE_NFT_ADDRESS: 0x90c4d6113ec88dd4bdf12f26db2b3998fd13a144