PORT: 3000
CLICKHOUSE_HOST: localhost
CLICKHOUSE_TCP_PORT: 9000
CLICKHOUSE_USER: admin
CLICKHOUSE_PASSWORD: password
CLICKHOUSE_DATABASE: dimo
TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
TOKEN_EXCHANGE_ISSUER_URL: http://127.0.0.1:5556/dex
VEHICLE_NFT_ADDRESS: 0x90c4d6113ec88dd4bdf12f26db2b3998fd13a144
MANUFACTURER_NFT_ADDRESS: 0xA4ad0F9c722588910791A9BAC63ADbB365614Bc7
S3_AWS_REGION: us-east-2
VINVC_BUCKET: dimo-network-vinvc-dev
VINVC_DATA_TYPE: 'VINVCv0.0'
S3_AWS_ACCESS_KEY_ID: "KEY_ID"
S3_AWS_SECRET_ACCESS_KEY: "Key"
IDENTITY_API_REQUEST_TIMEOUT_SECONDS: 5
DEVICE_LAST_SEEN_BIN_HOURS: 3
