// Code generated by MockGen. DO NOT EDIT.
// Source: ./repositories.go
//
// Generated by this command:
//
//	mockgen -source=./repositories.go -destination=repositories_mocks_test.go -package=repositories_test
//

// Package repositories_test is a generated GoMock package.
package repositories_test

import (
	context "context"
	reflect "reflect"
	time "time"

	vss "github.com/DIMO-Network/model-garage/pkg/vss"
	model "github.com/DIMO-Network/telemetry-api/internal/graph/model"
	ch "github.com/DIMO-Network/telemetry-api/internal/service/ch"
	gomock "go.uber.org/mock/gomock"
)

// MockCHService is a mock of CHService interface.
type MockCHService struct {
	ctrl     *gomock.Controller
	recorder *MockCHServiceMockRecorder
	isgomock struct{}
}

// MockCHServiceMockRecorder is the mock recorder for MockCHService.
type MockCHServiceMockRecorder struct {
	mock *MockCHService
}

// NewMockCHService creates a new mock instance.
func NewMockCHService(ctrl *gomock.Controller) *MockCHService {
	mock := &MockCHService{ctrl: ctrl}
	mock.recorder = &MockCHServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCHService) EXPECT() *MockCHServiceMockRecorder {
	return m.recorder
}

// GetAggregatedSignals mocks base method.
func (m *MockCHService) GetAggregatedSignals(ctx context.Context, aggArgs *model.AggregatedSignalArgs) ([]*ch.AggSignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedSignals", ctx, aggArgs)
	ret0, _ := ret[0].([]*ch.AggSignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedSignals indicates an expected call of GetAggregatedSignals.
func (mr *MockCHServiceMockRecorder) GetAggregatedSignals(ctx, aggArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedSignals", reflect.TypeOf((*MockCHService)(nil).GetAggregatedSignals), ctx, aggArgs)
}

// GetAggregatedSignalsForRanges mocks base method.
func (m *MockCHService) GetAggregatedSignalsForRanges(ctx context.Context, tokenID uint32, ranges []ch.TimeRange, globalFrom, globalTo time.Time, floatArgs []model.FloatSignalArgs, locationArgs []model.LocationSignalArgs) ([]*ch.AggSignalForRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedSignalsForRanges", ctx, tokenID, ranges, globalFrom, globalTo, floatArgs, locationArgs)
	ret0, _ := ret[0].([]*ch.AggSignalForRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedSignalsForRanges indicates an expected call of GetAggregatedSignalsForRanges.
func (mr *MockCHServiceMockRecorder) GetAggregatedSignalsForRanges(ctx, tokenID, ranges, globalFrom, globalTo, floatArgs, locationArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedSignalsForRanges", reflect.TypeOf((*MockCHService)(nil).GetAggregatedSignalsForRanges), ctx, tokenID, ranges, globalFrom, globalTo, floatArgs, locationArgs)
}

// GetAvailableSignals mocks base method.
func (m *MockCHService) GetAvailableSignals(ctx context.Context, tokenID uint32, filter *model.SignalFilter) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSignals", ctx, tokenID, filter)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSignals indicates an expected call of GetAvailableSignals.
func (mr *MockCHServiceMockRecorder) GetAvailableSignals(ctx, tokenID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSignals", reflect.TypeOf((*MockCHService)(nil).GetAvailableSignals), ctx, tokenID, filter)
}

// GetEventCounts mocks base method.
func (m *MockCHService) GetEventCounts(ctx context.Context, subject string, from, to time.Time, eventNames []string) ([]*ch.EventCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventCounts", ctx, subject, from, to, eventNames)
	ret0, _ := ret[0].([]*ch.EventCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventCounts indicates an expected call of GetEventCounts.
func (mr *MockCHServiceMockRecorder) GetEventCounts(ctx, subject, from, to, eventNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventCounts", reflect.TypeOf((*MockCHService)(nil).GetEventCounts), ctx, subject, from, to, eventNames)
}

// GetEventCountsForRanges mocks base method.
func (m *MockCHService) GetEventCountsForRanges(ctx context.Context, subject string, ranges []ch.TimeRange, eventNames []string) ([]*ch.EventCountForRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventCountsForRanges", ctx, subject, ranges, eventNames)
	ret0, _ := ret[0].([]*ch.EventCountForRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventCountsForRanges indicates an expected call of GetEventCountsForRanges.
func (mr *MockCHServiceMockRecorder) GetEventCountsForRanges(ctx, subject, ranges, eventNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventCountsForRanges", reflect.TypeOf((*MockCHService)(nil).GetEventCountsForRanges), ctx, subject, ranges, eventNames)
}

// GetEventSummaries mocks base method.
func (m *MockCHService) GetEventSummaries(ctx context.Context, subject string) ([]*ch.EventSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventSummaries", ctx, subject)
	ret0, _ := ret[0].([]*ch.EventSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventSummaries indicates an expected call of GetEventSummaries.
func (mr *MockCHServiceMockRecorder) GetEventSummaries(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventSummaries", reflect.TypeOf((*MockCHService)(nil).GetEventSummaries), ctx, subject)
}

// GetEvents mocks base method.
func (m *MockCHService) GetEvents(ctx context.Context, subject string, from, to time.Time, filter *model.EventFilter) ([]*vss.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, subject, from, to, filter)
	ret0, _ := ret[0].([]*vss.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockCHServiceMockRecorder) GetEvents(ctx, subject, from, to, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockCHService)(nil).GetEvents), ctx, subject, from, to, filter)
}

// GetLatestSignals mocks base method.
func (m *MockCHService) GetLatestSignals(ctx context.Context, latestArgs *model.LatestSignalsArgs) ([]*vss.Signal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSignals", ctx, latestArgs)
	ret0, _ := ret[0].([]*vss.Signal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSignals indicates an expected call of GetLatestSignals.
func (mr *MockCHServiceMockRecorder) GetLatestSignals(ctx, latestArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSignals", reflect.TypeOf((*MockCHService)(nil).GetLatestSignals), ctx, latestArgs)
}

// GetSegments mocks base method.
func (m *MockCHService) GetSegments(ctx context.Context, tokenID uint32, from, to time.Time, mechanism model.DetectionMechanism, config *model.SegmentConfig) ([]*model.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegments", ctx, tokenID, from, to, mechanism, config)
	ret0, _ := ret[0].([]*model.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegments indicates an expected call of GetSegments.
func (mr *MockCHServiceMockRecorder) GetSegments(ctx, tokenID, from, to, mechanism, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegments", reflect.TypeOf((*MockCHService)(nil).GetSegments), ctx, tokenID, from, to, mechanism, config)
}

// GetSignalSummaries mocks base method.
func (m *MockCHService) GetSignalSummaries(ctx context.Context, tokenID uint32, filter *model.SignalFilter) ([]*model.SignalDataSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignalSummaries", ctx, tokenID, filter)
	ret0, _ := ret[0].([]*model.SignalDataSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignalSummaries indicates an expected call of GetSignalSummaries.
func (mr *MockCHServiceMockRecorder) GetSignalSummaries(ctx, tokenID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignalSummaries", reflect.TypeOf((*MockCHService)(nil).GetSignalSummaries), ctx, tokenID, filter)
}
