replicaCount: 1
image:
  repository: dimozone/telemetry-api
  pullPolicy: IfNotPresent
  tag: fde4fd3
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
cronJob:
  enabled: false
  schedule: 0 0 * * 0
env:
  PORT: 8080
  MON_PORT: 8888
  CLICKHOUSE_TCP_PORT: 9440
  CLICKHOUSE_DATABASE: dimo
  TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://dex-roles-rights.dev.svc.cluster.local:5556/keys
  TOKEN_EXCHANGE_ISSUER_URL: https://auth-roles-rights.dev.dimo.zone
  VEHICLE_NFT_ADDRESS: '0x45fbCD3ef7361d156e8b16F5538AE36DEdf61Da8'
  MANUFACTURER_NFT_ADDRESS: '0xA4ad0F9c722588910791A9BAC63ADbB365614Bc7'
  MAX_REQUEST_DURATION: 5s
  S3_AWS_REGION: us-east-2
  VC_BUCKET: dimo-network-vc-dev
  VINVC_DATA_TYPE: VINVCv1.0
  POMVC_DATA_TYPE: POMVCv1.0
  CLICKHOUSE_FILE_INDEX_DATABASE: file_index
  IDENTITY_API_URL: https://identity-api.dev.dimo.zone/query
  IDENTITY_API_REQUEST_TIMEOUT_SECONDS: 5
  DEVICE_LAST_SEEN_BIN_HOURS: 3
  RUPTELA_CONNECTION_ID: '0x4Dc84a226102c08e911A5159e165e616e3A877A8'
  DIMO_REGISTRY_CHAIN_ID: 80002
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/limit-rps: '25'
    external-dns.alpha.kubernetes.io/hostname: telemetry-api.dev.dimo.zone
  hosts:
    - host: telemetry-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics: []
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
