// Code generated by "model-garage" DO NOT EDIT.
package model

import "github.com/DIMO-Network/model-garage/pkg/vss"

// SignalToLatestSignal converts a vss.Signal to a LatestSignal based on the signal name.
// Returns nil if the signal name is not recognized.
func SignalToLatestSignal(signal *vss.Signal) *LatestSignal {
	if signal == nil {
		return nil
	}
	switch signal.Data.Name {
	case "angularVelocityYaw":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "bodyLightsIsAirbagWarningOn":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "bodyLockIsLocked":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "bodyTrunkFrontIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "bodyTrunkRearIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow1DriverSideIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow1DriverSideWindowIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow1PassengerSideIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow1PassengerSideWindowIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow2DriverSideIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow2DriverSideWindowIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow2PassengerSideIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinDoorRow2PassengerSideWindowIsOpen":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow1DriverSideIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow1PassengerSideIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow2DriverSideIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow2MiddleIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow2PassengerSideIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow3DriverSideIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "cabinSeatRow3PassengerSideIsBelted":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow1WheelLeftSpeed":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow1WheelLeftTirePressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow1WheelRightSpeed":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow1WheelRightTirePressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow2WheelLeftTirePressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow2WheelRightTirePressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow3Weight":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow4Weight":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisAxleRow5Weight":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisBrakeABSIsWarningOn":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisBrakeCircuit1PressurePrimary":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisBrakeCircuit2PressurePrimary":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisBrakeIsPedalPressed":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisBrakePedalPosition":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisParkingBrakeIsEngaged":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "chassisTireSystemIsWarningOn":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "connectivityCellularIsJammingDetected":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "currentLocationAltitude":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "currentLocationCoordinates":
		return &LatestSignal{
			Name:      signal.Data.Name,
			Timestamp: signal.Data.Timestamp,
			ValueLocation: &Location{
				Latitude:  signal.Data.ValueLocation.Latitude,
				Longitude: signal.Data.ValueLocation.Longitude,
				Hdop:      signal.Data.ValueLocation.HDOP,
			},
		}
	case "currentLocationHeading":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "exteriorAirTemperature":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "isIgnitionOn":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "lowVoltageBatteryCurrentVoltage":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdBarometricPressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdCommandedEGR":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdCommandedEVAP":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdDTCList":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueString: &signal.Data.ValueString,
		}
	case "obdDistanceSinceDTCClear":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdDistanceWithMIL":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdEngineLoad":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdEthanolPercent":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdFuelPressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdFuelRailPressure":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdFuelRate":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdFuelTypeName":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueString: &signal.Data.ValueString,
		}
	case "obdIntakeTemp":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdIsEngineBlocked":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdIsPTOActive":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdIsPluggedIn":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdLongTermFuelTrim1":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdLongTermFuelTrim2":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdMAP":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdMaxMAF":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdO2WRSensor1Voltage":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdO2WRSensor2Voltage":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdOilTemperature":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdRunTime":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdShortTermFuelTrim1":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdStatusDTCCount":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdThrottlePosition":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "obdWarmupsSinceDTCClear":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineDieselExhaustFluidCapacity":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineDieselExhaustFluidLevel":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineECT":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineEOP":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineEOT":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineEngineOilLevel":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueString: &signal.Data.ValueString,
		}
	case "powertrainCombustionEngineEngineOilRelativeLevel":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineMAF":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineSpeed":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineTPS":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineTorque":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainCombustionEngineTorquePercent":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainFuelSystemAbsoluteLevel":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainFuelSystemAccumulatedConsumption":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainFuelSystemRelativeLevel":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainFuelSystemSupportedFuelTypes":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueString: &signal.Data.ValueString,
		}
	case "powertrainRange":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingAddedEnergy":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingChargeCurrentAC":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingChargeLimit":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingChargeVoltageUnknownType":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingIsCharging":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingIsChargingCableConnected":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryChargingPower":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryCurrentPower":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryCurrentVoltage":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryGrossCapacity":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryRange":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryStateOfChargeCurrent":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryStateOfChargeCurrentEnergy":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryStateOfHealth":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTractionBatteryTemperatureAverage":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionActualGear":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionActualGearRatio":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionCurrentGear":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionIsClutchSwitchOperated":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionRetarderActualTorque":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionRetarderTorqueMode":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueString: &signal.Data.ValueString,
		}
	case "powertrainTransmissionSelectedGear":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionTemperature":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainTransmissionTravelledDistance":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "powertrainType":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueString: &signal.Data.ValueString,
		}
	case "serviceDistanceToService":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "serviceTimeToService":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	case "speed":
		return &LatestSignal{
			Name:        signal.Data.Name,
			Timestamp:   signal.Data.Timestamp,
			ValueNumber: &signal.Data.ValueNumber,
		}
	}
	return nil
}

// SignalPrivileges maps signal JSON names to their required privilege names.
// These are the GraphQL enum values from the schema (e.g., "VEHICLE_NON_LOCATION_DATA").
var SignalPrivileges = map[string][]string{
	"angularVelocityYaw":                                        {"VEHICLE_NON_LOCATION_DATA"},
	"bodyLightsIsAirbagWarningOn":                               {"VEHICLE_NON_LOCATION_DATA"},
	"bodyLockIsLocked":                                          {"VEHICLE_NON_LOCATION_DATA"},
	"bodyTrunkFrontIsOpen":                                      {"VEHICLE_NON_LOCATION_DATA"},
	"bodyTrunkRearIsOpen":                                       {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow1DriverSideIsOpen":                             {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow1DriverSideWindowIsOpen":                       {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow1PassengerSideIsOpen":                          {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow1PassengerSideWindowIsOpen":                    {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow2DriverSideIsOpen":                             {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow2DriverSideWindowIsOpen":                       {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow2PassengerSideIsOpen":                          {"VEHICLE_NON_LOCATION_DATA"},
	"cabinDoorRow2PassengerSideWindowIsOpen":                    {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow1DriverSideIsBelted":                           {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow1PassengerSideIsBelted":                        {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow2DriverSideIsBelted":                           {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow2MiddleIsBelted":                               {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow2PassengerSideIsBelted":                        {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow3DriverSideIsBelted":                           {"VEHICLE_NON_LOCATION_DATA"},
	"cabinSeatRow3PassengerSideIsBelted":                        {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow1WheelLeftSpeed":                             {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow1WheelLeftTirePressure":                      {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow1WheelRightSpeed":                            {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow1WheelRightTirePressure":                     {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow2WheelLeftTirePressure":                      {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow2WheelRightTirePressure":                     {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow3Weight":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow4Weight":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"chassisAxleRow5Weight":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"chassisBrakeABSIsWarningOn":                                {"VEHICLE_NON_LOCATION_DATA"},
	"chassisBrakeCircuit1PressurePrimary":                       {"VEHICLE_NON_LOCATION_DATA"},
	"chassisBrakeCircuit2PressurePrimary":                       {"VEHICLE_NON_LOCATION_DATA"},
	"chassisBrakeIsPedalPressed":                                {"VEHICLE_NON_LOCATION_DATA"},
	"chassisBrakePedalPosition":                                 {"VEHICLE_NON_LOCATION_DATA"},
	"chassisParkingBrakeIsEngaged":                              {"VEHICLE_NON_LOCATION_DATA"},
	"chassisTireSystemIsWarningOn":                              {"VEHICLE_NON_LOCATION_DATA"},
	"connectivityCellularIsJammingDetected":                     {"VEHICLE_NON_LOCATION_DATA"},
	"currentLocationAltitude":                                   {"VEHICLE_ALL_TIME_LOCATION"},
	"currentLocationCoordinates":                                {"VEHICLE_ALL_TIME_LOCATION"},
	"currentLocationHeading":                                    {"VEHICLE_ALL_TIME_LOCATION"},
	"exteriorAirTemperature":                                    {"VEHICLE_NON_LOCATION_DATA"},
	"isIgnitionOn":                                              {"VEHICLE_NON_LOCATION_DATA"},
	"lowVoltageBatteryCurrentVoltage":                           {"VEHICLE_NON_LOCATION_DATA"},
	"obdBarometricPressure":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"obdCommandedEGR":                                           {"VEHICLE_NON_LOCATION_DATA"},
	"obdCommandedEVAP":                                          {"VEHICLE_NON_LOCATION_DATA"},
	"obdDTCList":                                                {"VEHICLE_NON_LOCATION_DATA"},
	"obdDistanceSinceDTCClear":                                  {"VEHICLE_NON_LOCATION_DATA"},
	"obdDistanceWithMIL":                                        {"VEHICLE_NON_LOCATION_DATA"},
	"obdEngineLoad":                                             {"VEHICLE_NON_LOCATION_DATA"},
	"obdEthanolPercent":                                         {"VEHICLE_NON_LOCATION_DATA"},
	"obdFuelPressure":                                           {"VEHICLE_NON_LOCATION_DATA"},
	"obdFuelRailPressure":                                       {"VEHICLE_NON_LOCATION_DATA"},
	"obdFuelRate":                                               {"VEHICLE_NON_LOCATION_DATA"},
	"obdFuelTypeName":                                           {"VEHICLE_NON_LOCATION_DATA"},
	"obdIntakeTemp":                                             {"VEHICLE_NON_LOCATION_DATA"},
	"obdIsEngineBlocked":                                        {"VEHICLE_NON_LOCATION_DATA"},
	"obdIsPTOActive":                                            {"VEHICLE_NON_LOCATION_DATA"},
	"obdIsPluggedIn":                                            {"VEHICLE_NON_LOCATION_DATA"},
	"obdLongTermFuelTrim1":                                      {"VEHICLE_NON_LOCATION_DATA"},
	"obdLongTermFuelTrim2":                                      {"VEHICLE_NON_LOCATION_DATA"},
	"obdMAP":                                                    {"VEHICLE_NON_LOCATION_DATA"},
	"obdMaxMAF":                                                 {"VEHICLE_NON_LOCATION_DATA"},
	"obdO2WRSensor1Voltage":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"obdO2WRSensor2Voltage":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"obdOilTemperature":                                         {"VEHICLE_NON_LOCATION_DATA"},
	"obdRunTime":                                                {"VEHICLE_NON_LOCATION_DATA"},
	"obdShortTermFuelTrim1":                                     {"VEHICLE_NON_LOCATION_DATA"},
	"obdStatusDTCCount":                                         {"VEHICLE_NON_LOCATION_DATA"},
	"obdThrottlePosition":                                       {"VEHICLE_NON_LOCATION_DATA"},
	"obdWarmupsSinceDTCClear":                                   {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineDieselExhaustFluidCapacity":      {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineDieselExhaustFluidLevel":         {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineECT":                             {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineEOP":                             {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineEOT":                             {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineEngineOilLevel":                  {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineEngineOilRelativeLevel":          {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineMAF":                             {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineSpeed":                           {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineTPS":                             {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineTorque":                          {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainCombustionEngineTorquePercent":                   {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainFuelSystemAbsoluteLevel":                         {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainFuelSystemAccumulatedConsumption":                {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainFuelSystemRelativeLevel":                         {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainFuelSystemSupportedFuelTypes":                    {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainRange":                                           {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingAddedEnergy":              {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingChargeCurrentAC":          {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingChargeLimit":              {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingChargeVoltageUnknownType": {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingIsCharging":               {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingIsChargingCableConnected": {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryChargingPower":                    {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryCurrentPower":                     {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryCurrentVoltage":                   {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryGrossCapacity":                    {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryRange":                            {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryStateOfChargeCurrent":             {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryStateOfChargeCurrentEnergy":       {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryStateOfHealth":                    {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTractionBatteryTemperatureAverage":               {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionActualGear":                          {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionActualGearRatio":                     {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionCurrentGear":                         {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionIsClutchSwitchOperated":              {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionRetarderActualTorque":                {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionRetarderTorqueMode":                  {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionSelectedGear":                        {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionTemperature":                         {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainTransmissionTravelledDistance":                   {"VEHICLE_NON_LOCATION_DATA"},
	"powertrainType":                                            {"VEHICLE_NON_LOCATION_DATA"},
	"serviceDistanceToService":                                  {"VEHICLE_NON_LOCATION_DATA"},
	"serviceTimeToService":                                      {"VEHICLE_NON_LOCATION_DATA"},
	"speed":                                                     {"VEHICLE_NON_LOCATION_DATA"},
}
