apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "telemetry-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/telemetry/clickhouse/host
    secretKey: CLICKHOUSE_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/telemetry/clickhouse/user
    secretKey: CLICKHOUSE_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/telemetry/clickhouse/pass
    secretKey: CLICKHOUSE_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "telemetry-api.fullname" . }}-secret
    template:
      metadata: {}
