// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth.go

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	identity "github.com/DIMO-Network/telemetry-api/internal/services/identity"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityService is a mock of IdentityService interface.
type MockIdentityService struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceMockRecorder
}

// MockIdentityServiceMockRecorder is the mock recorder for MockIdentityService.
type MockIdentityServiceMockRecorder struct {
	mock *MockIdentityService
}

// NewMockIdentityService creates a new mock instance.
func NewMockIdentityService(ctrl *gomock.Controller) *MockIdentityService {
	mock := &MockIdentityService{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityService) EXPECT() *MockIdentityServiceMockRecorder {
	return m.recorder
}

// GetAftermarketDevice mocks base method.
func (m *MockIdentityService) GetAftermarketDevice(ctx context.Context, address *common.Address, tokenID *int, serial *string) (*identity.DeviceInfos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAftermarketDevice", ctx, address, tokenID, serial)
	ret0, _ := ret[0].(*identity.DeviceInfos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAftermarketDevice indicates an expected call of GetAftermarketDevice.
func (mr *MockIdentityServiceMockRecorder) GetAftermarketDevice(ctx, address, tokenID, serial interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAftermarketDevice", reflect.TypeOf((*MockIdentityService)(nil).GetAftermarketDevice), ctx, address, tokenID, serial)
}
