// Code generated by MockGen. DO NOT EDIT.
// Source: vc.go
//
// Generated by this command:
//
//	mockgen -source=vc.go -destination=vc_mock_test.go -package=vc_test
//

// Package vc_test is a generated GoMock package.
package vc_test

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	"github.com/DIMO-Network/cloudevent"
	grpc "github.com/DIMO-Network/fetch-api/pkg/grpc"
	gomock "go.uber.org/mock/gomock"
)

// MockindexRepoService is a mock of indexRepoService interface.
type MockindexRepoService struct {
	ctrl     *gomock.Controller
	recorder *MockindexRepoServiceMockRecorder
	isgomock struct{}
}

// MockindexRepoServiceMockRecorder is the mock recorder for MockindexRepoService.
type MockindexRepoServiceMockRecorder struct {
	mock *MockindexRepoService
}

// NewMockindexRepoService creates a new mock instance.
func NewMockindexRepoService(ctrl *gomock.Controller) *MockindexRepoService {
	mock := &MockindexRepoService{ctrl: ctrl}
	mock.recorder = &MockindexRepoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockindexRepoService) EXPECT() *MockindexRepoServiceMockRecorder {
	return m.recorder
}

// GetLatestCloudEvent mocks base method.
func (m *MockindexRepoService) GetLatestCloudEvent(ctx context.Context, filter *grpc.SearchOptions) (cloudevent.CloudEvent[json.RawMessage], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestCloudEvent", ctx, filter)
	ret0, _ := ret[0].(cloudevent.CloudEvent[json.RawMessage])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestCloudEvent indicates an expected call of GetLatestCloudEvent.
func (mr *MockindexRepoServiceMockRecorder) GetLatestCloudEvent(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestCloudEvent", reflect.TypeOf((*MockindexRepoService)(nil).GetLatestCloudEvent), ctx, filter)
}
