package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/DIMO-Network/telemetry-api/internal/graph/model"
)

// Signals is the resolver for the Signals field.
func (r *queryResolver) Signals(ctx context.Context, tokenID *string, from *time.Time, to *time.Time) (*model.SignalCollection, error) {
	tokenIDInt, err := strconv.ParseUint(*tokenID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("failed to convert tokenID to int: %w", err)
	}
	return &model.SignalCollection{TokenID: uint32(tokenIDInt)}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SignalCollection returns SignalCollectionResolver implementation.
func (r *Resolver) SignalCollection() SignalCollectionResolver { return &signalCollectionResolver{r} }

type queryResolver struct{ *Resolver }
type signalCollectionResolver struct{ *Resolver }
