package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/DIMO-Network/model-garage/pkg/vss"
	"github.com/DIMO-Network/telemetry-api/internal/graph/model"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// DIMOData is the resolver for the DIMOData field.
func (r *queryResolver) DIMOData(ctx context.Context, page model.PageSelection, filterBy *model.DimosFilter) (*model.DimoConnection, error) {
	// get requestd Cols

	cols := GetPreloads(ctx)
	queryCols := make([]string, 0, len(cols))
	for i := range cols {
		val, ok := vss.DimoJSONName2CHName[cols[i]]
		if ok {
			queryCols = append(queryCols, val)
		}
	}

	return r.GetDIMOData(ctx, queryCols, page, filterBy)
}

// Signals is the resolver for the Signals field.
func (r *queryResolver) Signals(ctx context.Context, tokenID *string, from *time.Time, to *time.Time) (*model.SignalCollection, error) {
	tokenIDInt, err := strconv.ParseUint(*tokenID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("failed to convert tokenID to int: %w", err)
	}
	return &model.SignalCollection{TokenID: uint32(tokenIDInt)}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SignalCollection returns SignalCollectionResolver implementation.
func (r *Resolver) SignalCollection() SignalCollectionResolver { return &signalCollectionResolver{r} }

type queryResolver struct{ *Resolver }
type signalCollectionResolver struct{ *Resolver }
