package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/DIMO-Network/telemetry-api/internal/graph/model"
)

// CurrentLocation is the resolver for the currentLocation field.
func (r *signalAggregationsResolver) CurrentLocation(ctx context.Context, obj *model.SignalAggregations, agg model.LocationAggregation, filter *model.SignalLocationFilter) (*model.Location, error) {
	fieldCtx := graphql.GetFieldContext(ctx)
	vl, ok := obj.ValueLocations[fieldCtx.Field.Alias]
	if !ok {
		return nil, nil
	}
	return &vl, nil
}
