package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/DIMO-Network/telemetry-api/internal/graph/model"
)

// VehicleChassisAxleRow1WheelLeftTirePressure is the resolver for the vehicleChassisAxleRow1WheelLeftTirePressure field.
func (r *signalCollectionResolver) VehicleChassisAxleRow1WheelLeftTirePressure(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleChassisAxleRow1WheelRightTirePressure is the resolver for the vehicleChassisAxleRow1WheelRightTirePressure field.
func (r *signalCollectionResolver) VehicleChassisAxleRow1WheelRightTirePressure(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleChassisAxleRow2WheelLeftTirePressure is the resolver for the vehicleChassisAxleRow2WheelLeftTirePressure field.
func (r *signalCollectionResolver) VehicleChassisAxleRow2WheelLeftTirePressure(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleChassisAxleRow2WheelRightTirePressure is the resolver for the vehicleChassisAxleRow2WheelRightTirePressure field.
func (r *signalCollectionResolver) VehicleChassisAxleRow2WheelRightTirePressure(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleCurrentLocationAltitude is the resolver for the vehicleCurrentLocationAltitude field.
func (r *signalCollectionResolver) VehicleCurrentLocationAltitude(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleCurrentLocationLatitude is the resolver for the vehicleCurrentLocationLatitude field.
func (r *signalCollectionResolver) VehicleCurrentLocationLatitude(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleCurrentLocationLongitude is the resolver for the vehicleCurrentLocationLongitude field.
func (r *signalCollectionResolver) VehicleCurrentLocationLongitude(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleCurrentLocationTimestamp is the resolver for the vehicleCurrentLocationTimestamp field.
func (r *signalCollectionResolver) VehicleCurrentLocationTimestamp(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehicleExteriorAirTemperature is the resolver for the vehicleExteriorAirTemperature field.
func (r *signalCollectionResolver) VehicleExteriorAirTemperature(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleLowVoltageBatteryCurrentVoltage is the resolver for the vehicleLowVoltageBatteryCurrentVoltage field.
func (r *signalCollectionResolver) VehicleLowVoltageBatteryCurrentVoltage(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleOBDBarometricPressure is the resolver for the vehicleOBDBarometricPressure field.
func (r *signalCollectionResolver) VehicleOBDBarometricPressure(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleOBDEngineLoad is the resolver for the vehicleOBDEngineLoad field.
func (r *signalCollectionResolver) VehicleOBDEngineLoad(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleOBDIntakeTemp is the resolver for the vehicleOBDIntakeTemp field.
func (r *signalCollectionResolver) VehicleOBDIntakeTemp(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleOBDRunTime is the resolver for the vehicleOBDRunTime field.
func (r *signalCollectionResolver) VehicleOBDRunTime(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainCombustionEngineEct is the resolver for the VehiclePowertrainCombustionEngineEct field.
func (r *signalCollectionResolver) VehiclePowertrainCombustionEngineEct(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainCombustionEngineEngineOilLevel is the resolver for the vehiclePowertrainCombustionEngineEngineOilLevel field.
func (r *signalCollectionResolver) VehiclePowertrainCombustionEngineEngineOilLevel(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehiclePowertrainCombustionEngineSpeed is the resolver for the vehiclePowertrainCombustionEngineSpeed field.
func (r *signalCollectionResolver) VehiclePowertrainCombustionEngineSpeed(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainCombustionEngineTps is the resolver for the VehiclePowertrainCombustionEngineTps field.
func (r *signalCollectionResolver) VehiclePowertrainCombustionEngineTps(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainFuelSystemAbsoluteLevel is the resolver for the vehiclePowertrainFuelSystemAbsoluteLevel field.
func (r *signalCollectionResolver) VehiclePowertrainFuelSystemAbsoluteLevel(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainFuelSystemSupportedFuelTypes is the resolver for the vehiclePowertrainFuelSystemSupportedFuelTypes field.
func (r *signalCollectionResolver) VehiclePowertrainFuelSystemSupportedFuelTypes(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehiclePowertrainRange is the resolver for the vehiclePowertrainRange field.
func (r *signalCollectionResolver) VehiclePowertrainRange(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainTractionBatteryChargingChargeLimit is the resolver for the vehiclePowertrainTractionBatteryChargingChargeLimit field.
func (r *signalCollectionResolver) VehiclePowertrainTractionBatteryChargingChargeLimit(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainTractionBatteryChargingIsCharging is the resolver for the vehiclePowertrainTractionBatteryChargingIsCharging field.
func (r *signalCollectionResolver) VehiclePowertrainTractionBatteryChargingIsCharging(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehiclePowertrainTractionBatteryGrossCapacity is the resolver for the vehiclePowertrainTractionBatteryGrossCapacity field.
func (r *signalCollectionResolver) VehiclePowertrainTractionBatteryGrossCapacity(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainTractionBatteryStateOfChargeCurrent is the resolver for the vehiclePowertrainTractionBatteryStateOfChargeCurrent field.
func (r *signalCollectionResolver) VehiclePowertrainTractionBatteryStateOfChargeCurrent(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainTransmissionTravelledDistance is the resolver for the vehiclePowertrainTransmissionTravelledDistance field.
func (r *signalCollectionResolver) VehiclePowertrainTransmissionTravelledDistance(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehiclePowertrainType is the resolver for the vehiclePowertrainType field.
func (r *signalCollectionResolver) VehiclePowertrainType(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehicleSpeed is the resolver for the vehicleSpeed field.
func (r *signalCollectionResolver) VehicleSpeed(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}

// VehicleVehicleIdentificationBrand is the resolver for the vehicleVehicleIdentificationBrand field.
func (r *signalCollectionResolver) VehicleVehicleIdentificationBrand(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehicleVehicleIdentificationModel is the resolver for the vehicleVehicleIdentificationModel field.
func (r *signalCollectionResolver) VehicleVehicleIdentificationModel(ctx context.Context, obj *model.SignalCollection, agg *model.StringAggregation) ([]*model.SignalString, error) {
	sigArgs, err := getStringArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalString(ctx, sigArgs)
}

// VehicleVehicleIdentificationYear is the resolver for the vehicleVehicleIdentificationYear field.
func (r *signalCollectionResolver) VehicleVehicleIdentificationYear(ctx context.Context, obj *model.SignalCollection, agg *model.FloatAggregation) ([]*model.SignalFloat, error) {
	sigArgs, err := getFloatArgs(ctx, obj, agg)
	if err != nil {
		return nil, err
	}
	return r.GetSignalFloats(ctx, sigArgs)
}
