package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/DIMO-Network/telemetry-api/internal/graph/model"
)

// Vinvc is the resolver for the vinvc field.
func (r *queryResolver) Vinvc(ctx context.Context, tokenID int) (*model.Vinvc, error) {
	return r.VINVCRepo.GetLatestVC(ctx, uint32(tokenID))
}
