name: buildpushdev
on:
  push:
    branches:
      - main
jobs:
  build:
    name: buildpushdev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/telemetry-api:${{ steps.slug.outputs.sha7 }}, dimozone/telemetry-api:latest

      - name: Update Image Version in the worker HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'charts/telemetry-api/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.slug.outputs.sha7 }}
          branch: main
          message: 'Update Image Version to ${{ steps.slug.outputs.sha7 }}'
