name: generate files
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    # Condition to skip merge commits
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: go mod tidy
        run: go mod tidy

      - name: go mod verify
        run: go mod verify

      - name: install tools
        run: make tools

      - name: generate graphql files
        run: make generate

      - name: porcelain
        shell: bash
        run: |
          dirty_files="$(git status --porcelain)"
          if [[ `git status --porcelain` ]]; then
            echo "The following files are dirty after running generators:"
            echo "${dirty_files}"
            exit 1
          fi