name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    # Condition to skip merge commits
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: false
          args: --modules-download-mode=readonly --timeout=10m
