name: gotest

on:
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t ./...
          go install gotest.tools/gotestsum@latest

      - name: modVerify
        run: go mod verify

      - name: Run Tests
        run: make test