name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    # Condition to skip merge commits
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: modVerify
        run: go mod verify

      - name: Run Tests
        run: make test